apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
data:
  botToken: {{ .Values.secrets.botToken | b64enc }}
  clientId: {{ .Values.secrets.clientId | b64enc }}
  guildId: {{ .Values.secrets.guildId | b64enc }}
  rapidApiKey: {{ .Values.secrets.rapidApiKey | b64enc }}
