apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
data:
  botToken: {{ .Values.secrets.botToken | b64enc }}
  clientId: {{ .Values.secrets.clientId | quote | b64enc }}
  guildId: {{ .Values.secrets.guildId | quote | b64enc }}
  rapidApiKey: {{ .Values.secrets.rapidApiKey | b64enc }}
  voiceRssKey: {{ .Values.secrets.voiceRssKey | b64enc }}
  discord22RootApiKey: {{ .Values.secrets.discord22RootApiKey | b64enc }}
