name: Deploy Bot

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_push:
    runs-on: ubuntu-latest
    environment: main

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Get short commit hash
        id: commit_hash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/kou-yagami:${{ steps.commit_hash.outputs.sha_short }}

  deploy_tencent:
    runs-on: ubuntu-latest
    needs: [build_push]
    environment: main

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Get short commit hash
        id: commit_hash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Deploy commands to Eagle Jump
        run: |
          yarn
          yarn run deploy-commands

      - name: Deploy bot to Cluster
        uses: wahyd4/kubectl-helm-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: |
            helm upgrade \
            --install kou-yagami charts/kou-yagami \
            --set image.tag=${{ steps.commit_hash.outputs.sha_short }} \
            --set secrets.botToken=${{ secrets.BOT_TOKEN }} \
            --set secrets.clientId=${{ secrets.CLIENT_ID }} \
            --set secrets.guildId=${{ secrets.GUILD_ID }} \
            --set secrets.rapidApiKey=${{ secrets.RAPID_API_KEY }}
